name: Publish Custom Rules

on:
  push:
    branches:
      - 'main'        # matches only main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install snyk-iac-rules
        run: npm i -g snyk-iac-rules
        
      - name: Build bundle
        run: snyk-iac-rules build .
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.OCI_REGISTRY_USERNAME }}
          password: ${{ secrets.OCI_REGISTRY_PASSWORD }}

      - name: Publish rules
        run: snyk-iac-rules push --registry $OCI_REGISTRY_URL bundle.tar.gz
        env:
          OCI_REGISTRY_URL: "${{ secrets.OCI_REGISTRY_NAME }}:v1"

      - name: Update Snyk
        run: |
          curl --location --request PATCH 'https://api.snyk.io/v3/orgs/${{ secrets.SNYK_ORG_PUBLIC_ID }}/settings/iac/?version=2021-12-09' \
          --header 'Content-Type: application/vnd.api+json' \
          --header 'Authorization: token ${{ secrets.SNYK_TOKEN }}' \
          --data-raw '{
          "data": {
                  "type": "iac_settings",
                  "attributes": {
                      "custom_rules": {
                      "oci_registry_url": "https://registry-1.${{ secrets.OCI_REGISTRY_NAME }}",
                          "oci_registry_tag": "v1",
                          "is_enabled": true
                      }
                  }
              }
          }'
